name: mlinstall
base: core24
version: '0.2.0'
summary: An app to assist with installing Magic Lantern.
description: |
  This is the description for MLinstall. You can use this space to describe
  how the app assists with installing Magic Lantern. Keep the description concise.

grade: devel
confinement: devmode

parts:
  my-part:
    plugin: dump
    source: .
    organize:
      lib/x86_64-linux-gnu/libui.so: lib/x86_64-linux-gnu/libui.so
      lib/x86_64-linux-gnu/libusb-1.0.so: lib/x86_64-linux-gnu/libusb-1.0.so

apps:
  mlinstall:
    command: env LD_LIBRARY_PATH=$SNAP/lib/x86_64-linux-gnu bin/linux.out
    plugs:
      - network
      - home
      - raw-usb
      - mount-observe
      - system-observe
      - block-devices
      - removable-media
      - hardware-observe
