name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Checkout submodules
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git submodule update --init --recursive
    
    - name: Install deps
      run: sudo apt install libusb-1.0-0-dev gcc libgtk-3-dev 
    
    - name: Compile
      run: cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build

    - name: Install mingw dependencies
      run: sudo apt install gcc-mingw-w64-base g++-mingw-w64-x86-64-win32

    - name: Compile for windows
      run: |
        cmake -DCMAKE_TOOLCHAIN_FILE=.github/workflows/mingw.cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -B build_win
        cmake --build build_win

  macOS-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: brew install libusb

    - name: Build
      run: make unix-gtk
