name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Checkout submodules
      run: git submodule update --init --recursive
    
    - name: Install deps
      run: sudo apt install libusb-1.0-0-dev gcc libgtk-3-dev
    
    - name: Compile
      run: make unix-gtk
